{
    "Coins": [
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="4",
                    tilewidth=128,
                    tileheight=128,
                    source="images/coin_01.png",
                    points=None,
                ),
                center_x=704,
                center_y=704,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="4",
                    tilewidth=128,
                    tileheight=128,
                    source="images/coin_01.png",
                    points=None,
                ),
                center_x=4032,
                center_y=704,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="4",
                    tilewidth=128,
                    tileheight=128,
                    source="images/coin_01.png",
                    points=None,
                ),
                center_x=5440,
                center_y=576,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="4",
                    tilewidth=128,
                    tileheight=128,
                    source="images/coin_01.png",
                    points=None,
                ),
                center_x=3392,
                center_y=448,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
    ],
    "Platforms": [
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="1",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassLeft.png",
                    points=None,
                ),
                center_x=3264,
                center_y=832,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3392,
                center_y=832,
            ),
            GridLocation(
                tile=Tile(
                    gid="3",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassRight.png",
                    points=None,
                ),
                center_x=3520,
                center_y=832,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
        ],
        [
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=64,
                center_y=576,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="1",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassLeft.png",
                    points=None,
                ),
                center_x=2624,
                center_y=576,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2752,
                center_y=576,
            ),
            GridLocation(
                tile=Tile(
                    gid="3",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassRight.png",
                    points=None,
                ),
                center_x=2880,
                center_y=576,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="1",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassLeft.png",
                    points=None,
                ),
                center_x=3904,
                center_y=576,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4032,
                center_y=576,
            ),
            GridLocation(
                tile=Tile(
                    gid="3",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassRight.png",
                    points=None,
                ),
                center_x=4160,
                center_y=576,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=6336,
                center_y=576,
            ),
        ],
        [
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=64,
                center_y=448,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="1",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassLeft.png",
                    points=None,
                ),
                center_x=576,
                center_y=448,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=704,
                center_y=448,
            ),
            GridLocation(
                tile=Tile(
                    gid="3",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassRight.png",
                    points=None,
                ),
                center_x=832,
                center_y=448,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=2112,
                center_y=448,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=4032,
                center_y=448,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5440,
                center_y=448,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=6336,
                center_y=448,
            ),
        ],
        [
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=64,
                center_y=320,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=2112,
                center_y=320,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=2240,
                center_y=320,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="1",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassLeft.png",
                    points=None,
                ),
                center_x=3264,
                center_y=320,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3392,
                center_y=320,
            ),
            GridLocation(
                tile=Tile(
                    gid="3",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassRight.png",
                    points=None,
                ),
                center_x=3520,
                center_y=320,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=4032,
                center_y=320,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5312,
                center_y=320,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5440,
                center_y=320,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5568,
                center_y=320,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=6336,
                center_y=320,
            ),
        ],
        [
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=64,
                center_y=192,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=1216,
                center_y=192,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=1984,
                center_y=192,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=2112,
                center_y=192,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=2240,
                center_y=192,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=4032,
                center_y=192,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=4416,
                center_y=192,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5184,
                center_y=192,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5312,
                center_y=192,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5440,
                center_y=192,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5568,
                center_y=192,
            ),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=5696,
                center_y=192,
            ),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(tile=None, center_x=None, center_y=None),
            GridLocation(
                tile=Tile(
                    gid="0",
                    tilewidth=128,
                    tileheight=128,
                    source="images/boxCrate_double.png",
                    points=None,
                ),
                center_x=6336,
                center_y=192,
            ),
        ],
        [
            GridLocation(
                tile=Tile(
                    gid="1",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassLeft.png",
                    points=None,
                ),
                center_x=64,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=192,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=320,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=448,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=576,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=704,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=832,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=960,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1088,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1216,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1344,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1472,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1600,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1728,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1856,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=1984,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2112,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2240,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2368,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2496,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2624,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2752,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=2880,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3008,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3136,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3264,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3392,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3520,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3648,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3776,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=3904,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4032,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4160,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4288,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4416,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4544,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4672,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4800,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=4928,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5056,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5184,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5312,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5440,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5568,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5696,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5824,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=5952,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=6080,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="2",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassMid.png",
                    points=None,
                ),
                center_x=6208,
                center_y=64,
            ),
            GridLocation(
                tile=Tile(
                    gid="3",
                    tilewidth=128,
                    tileheight=128,
                    source="images/grassRight.png",
                    points=None,
                ),
                center_x=6336,
                center_y=64,
            ),
        ],
    ],
}
