{   'background_color': None,
    'height': 6,
    'hex_side_length': None,
    'infinite': False,
    'layers': [   Layer(width=8, height=6, data=[[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32], [33, 34, 35, 36, 37, 38, 39, 40], [41, 42, 43, 44, 45, 46, 47, 48]], id=1, name='Tile Layer 1', offset=OrderedPair(x=0, y=0), opacity=255, properties=None)],
    'next_layer_id': 2,
    'next_object_id': 1,
    'orientation': 'orthogonal',
    'parent_dir': PosixPath('/home/ben/Projects/pytiled_parser/pytiled_parser-venv/pytiled_parser/tests/test_data'),
    'properties': {   'bool property - false': False,
                      'bool property - true': True,
                      'color property': Color(red=73, green=252, blue=255, alpha=255),
                      'file property': PosixPath('/var/log/syslog'),
                      'float property': 1.23456789,
                      'int property': 13,
                      'string property': 'Hello, World!!'},
    'render_order': 'right-down',
    'stagger_axis': None,
    'stagger_index': None,
    'tile_height': 32,
    'tile_sets': {   1: TileSet(name='tile_set_image', max_tile_size=OrderedPair(x=32, y=32), spacing=1, margin=1, tile_count=48, columns=8, tile_offset=None, grid=None, properties=None, image=Image(source='images/tmw_desert_spacing.png', trans=None, width=265, height=199), terrain_types=None, tiles={})},
    'tile_width': 32,
    'tiled_version': '1.2.3',
    'version': '1.2',
    'width': 8}
